export const navigationLinks = [
  {
    href: "/libraty",
    label: "Library",
  },
  {
    img: "user.svg",
    selectedImg: "user-fill.svg",
    href: "/my-profile",
    label: "My profile",
  },
];

export const adminSideBarLinks = [
  {
    img: " home.svg",
    route: "/admin",
    text: "Home",
  },
];

export const FIELD_NAMES = {
  fullname: "Full name",
  email: "Email address",
  universityid: "University ID Number",
  password: "Password",
  universityCard: "Upload university ID Card",
};

export const FIELD_TYPES = {
  fullname: "text",
  email: "email",
  universityid: "umber",
  password: "password",
};

export const sampleBooks = [
  {
    id: 1,
    title: "Tarzan",
    author: "Edgar Berrous",
    genre: "Fantasy",
    rating: 4.6,
    total_copies: 20,
    available_copies: 10,
    description: "Book about Strong Man and Many Monkeys",
    color: "#1c1f40",
    cover: "https://m.media-amazon.com/images/I/81J6APjwxlL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Tarzan's adventures in the jungle",
  },
  {
    id: 2,
    title: "Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "Detective",
    rating: 4.9,
    total_copies: 15,
    available_copies: 7,
    description: "Adventures of detective Sherlock Holmes",
    color: "#2a2f4a",
    cover: "https://m.media-amazon.com/images/I/91K5kU5fQeL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Holmes solves mysterious cases in London",
  },
  {
    id: 3,
    title: "Harry Potter",
    author: "J.K. Rowling",
    genre: "Fantasy",
    rating: 4.8,
    total_copies: 25,
    available_copies: 12,
    description: "A wizarding world filled with magic and friendship",
    color: "#3e1f47",
    cover: "https://m.media-amazon.com/images/I/81iqZ2HHD-L.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Harry discovers he is a wizard and attends Hogwarts",
  },
  {
    id: 4,
    title: "Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    rating: 4.9,
    total_copies: 18,
    available_copies: 5,
    description: "Epic journey in Middle-earth",
    color: "#1b2f3b",
    cover: "https://m.media-amazon.com/images/I/91SZSW8qSsL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Frodo and friends travel to destroy the One Ring",
  },
  {
    id: 5,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    rating: 4.7,
    total_copies: 20,
    available_copies: 9,
    description: "Dystopian society under constant surveillance",
    color: "#3a3a3a",
    cover: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Life under Big Brother's watchful eye",
  },
  {
    id: 6,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    rating: 4.8,
    total_copies: 22,
    available_copies: 11,
    description: "Bilbo Baggins' adventure to the Lonely Mountain",
    color: "#2d3e50",
    cover: "https://m.media-amazon.com/images/I/91b0C2YNSrL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Bilbo joins dwarves on a quest to reclaim treasure",
  },
  {
    id: 7,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    rating: 4.6,
    total_copies: 17,
    available_copies: 8,
    description: "Love and society in 19th-century England",
    color: "#5b3a29",
    cover: "https://m.media-amazon.com/images/I/91HHqVTAJQL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Elizabeth Bennet navigates love and societal norms",
  },
  {
    id: 8,
    title: "Moby Dick",
    author: "Herman Melville",
    genre: "Adventure",
    rating: 4.5,
    total_copies: 16,
    available_copies: 6,
    description: "Captain Ahab hunts the white whale",
    color: "#1e2d3b",
    cover: "https://m.media-amazon.com/images/I/81prVhtcI9L.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Ahab's obsession with the whale leads to tragedy",
  },
  {
    id: 9,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    rating: 4.4,
    total_copies: 18,
    available_copies: 7,
    description: "The Jazz Age and the American dream",
    color: "#2f2f2f",
    cover: "https://m.media-amazon.com/images/I/81af+MCATTL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Gatsby's pursuit of love and wealth in 1920s NYC",
  },
  {
    id: 10,
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Horror",
    rating: 4.5,
    total_copies: 14,
    available_copies: 5,
    description: "A scientist creates life and faces consequences",
    color: "#3d3d3d",
    cover: "https://m.media-amazon.com/images/I/71dh0OGLmLL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Victor Frankenstein's monster terrorizes humanity",
  },
  {
    id: 11,
    title: "Dracula",
    author: "Bram Stoker",
    genre: "Horror",
    rating: 4.6,
    total_copies: 12,
    available_copies: 5,
    description: "Count Dracula spreads terror in England",
    color: "#1c1c1c",
    cover: "https://m.media-amazon.com/images/I/81bXZL2T2bL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Dracula arrives in London to find new victims",
  },
  {
    id: 12,
    title: "Alice in Wonderland",
    author: "Lewis Carroll",
    genre: "Fantasy",
    rating: 4.7,
    total_copies: 20,
    available_copies: 10,
    description: "Alice's adventures in a magical world",
    color: "#5a2e8a",
    cover: "https://m.media-amazon.com/images/I/81etfP4yG-L.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Alice falls into Wonderland and meets strange creatures",
  },
  {
    id: 13,
    title: "The Odyssey",
    author: "Homer",
    genre: "Epic",
    rating: 4.8,
    total_copies: 15,
    available_copies: 7,
    description: "Odysseus' journey home after the Trojan War",
    color: "#2f3b4a",
    cover: "https://m.media-amazon.com/images/I/81Xwjl6tpCL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Epic voyage with monsters and gods",
  },
  {
    id: 14,
    title: "The Iliad",
    author: "Homer",
    genre: "Epic",
    rating: 4.7,
    total_copies: 17,
    available_copies: 8,
    description: "The Trojan War recounted",
    color: "#3a3f50",
    cover: "https://m.media-amazon.com/images/I/91w2jBXXv5L.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "War, heroes, and the wrath of Achilles",
  },
  {
    id: 15,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    genre: "Adventure",
    rating: 4.5,
    total_copies: 18,
    available_copies: 9,
    description: "Adventures of a delusional knight",
    color: "#4b3a2f",
    cover: "https://m.media-amazon.com/images/I/81s6DUyQCZL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Don Quixote fights windmills and pursues honor",
  },
  {
    id: 16,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    rating: 4.3,
    total_copies: 20,
    available_copies: 11,
    description: "Teenage angst and alienation",
    color: "#2b2b2b",
    cover: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Holden Caulfield navigates adulthood",
  },
  {
    id: 17,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    rating: 4.7,
    total_copies: 15,
    available_copies: 7,
    description: "A shepherd's journey to fulfill his dreams",
    color: "#3c2f50",
    cover: "https://m.media-amazon.com/images/I/71aFt4+OTOL.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Santiago searches for treasure and wisdom",
  },
  {
    id: 18,
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    genre: "Children",
    rating: 4.9,
    total_copies: 22,
    available_copies: 12,
    description: "A young prince explores different planets",
    color: "#5a2f3c",
    cover: "https://m.media-amazon.com/images/I/81a2sco+H4L.jpg",
    video: "https://youtu.be/3K3W_Gfd-e0?list=RD3_CrabwOWaU",
    summary: "Life lessons from the Little Prince",
  },
];
